apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-zgmn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hugares/rhtap-demo-cqiy-tenant/quarkus/devfile-sample-code-with-quarkus-zgmn@sha256:25b73524f316ecdb47e2d4d37945382abfa49eb52038e93546458a485c758318
        name: my-java-quarkus
        resources: {}
status: {}
